name: Update Vim

on:
  schedule:
    - cron: "0 0 * * 0"   # every Sunday at midnight UTC
  workflow_dispatch:       # allow manual trigger

permissions:
  contents: write

jobs:
  update-vim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget dpkg-dev grep

      - name: Get latest Vim version
        id: get_version
        run: |
          BASE_URL="https://packages.termux.dev/apt/termux-main/pool/main/v/vim/"
          # Find the latest ARM package (sorted by version)
          wget -qO- "$BASE_URL" | grep -o 'vim_[0-9.]\+-[0-9]\+_arm\.deb' | sort -V | tail -n1 > latest.txt
          FILE=$(cat latest.txt)
          VERSION=$(echo "$FILE" | sed -E 's/vim_([0-9.]+-[0-9]+)_.*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "Latest Vim version: $VERSION"

      - name: Download and extract Vim for all ABIs
        run: |
          BASE_URL="https://packages.termux.dev/apt/termux-main/pool/main/v/vim/"
          VERSION="${{ steps.get_version.outputs.version }}"

          declare -A archs=(
            [aarch64]=arm64
            [arm]=arm
            [i686]=x86
            [x86_64]=x86_64
          )

          rm -rf assets/vim
          mkdir -p assets/vim

          for arch in "${!archs[@]}"; do
            abi="${archs[$arch]}"
            FILE="vim_${VERSION}_${arch}.deb"
            URL="$BASE_URL$FILE"
            echo "Downloading $URL"
            wget -q "$URL" -O "$FILE" || { echo "⚠️ Failed to download $FILE"; continue; }
            
            mkdir -p "assets/vim/$abi/tmp"
            dpkg-deb -x "$FILE" "assets/vim/$abi/tmp"

            BIN_PATH="assets/vim/$abi/tmp/data/data/com.termux/files/usr/bin/vim"
            if [ -f "$BIN_PATH" ]; then
              mv "$BIN_PATH" "assets/vim/$abi/vim"
              chmod +x "assets/vim/$abi/vim"
              echo "✅ Extracted Vim for $abi"
            else
              echo "⚠️ Vim binary not found for $abi"
            fi

            rm -rf "assets/vim/$abi/tmp"
            rm -f "$FILE"
          done

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/vim
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Vim to version ${{ steps.get_version.outputs.version }}"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          fi
